on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Zip repository
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./repo.zip ./

      - name: Checkout remote repository
        uses: actions/checkout@v2
        with:
          repository: PrestigeCodeWorldwide/bigger_launcher  
          token: ${{ secrets.GITHUB_TOKEN }}  # replace with your secret token for the remote repo
          path: remote-repo

      - name: Move zipped repo to remote repository
        run: |
          mv repo.zip remote-repo/
          cd remote-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git add .
          git commit -m "Add zipped repo"
      
      - name: Push zipped repo to remote repository
        run: |       
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"   
          git fetch origin
          git push origin master
